{
  "records": {
    "2018-10-28T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-10-28T00:00:20.567917-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-10-29T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-10-29T00:00:32.176788-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.092629-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.612269-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.733479-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.814110-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.902906-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:40.998867-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:42.770735-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-29T03:01:42.858904-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-10-30T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-10-30T03:25:38.866665-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:39.353475-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:39.466787-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:39.527441-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:39.592184-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:39.657924-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:40.819284-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T03:25:40.894598-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:30:26.148383-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:30:32.135386-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded team.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:31:09.348355-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 3,
        "date": "2018-10-30T09:57:09.083386-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:55:08.215724-07:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 245, in _reload_internal\n    module, ok = importlib.import_module(package), True\n  File \"/usr/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 673, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/home/pi/filefairy/util/team/team.py\", line 30, in <module>\n    ('orange', 'red', 'yellow'),\nTypeError: 'str' object is not callable",
        "levelname": "INFO",
        "lineno": 254,
        "msg": "Disabled team.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:55:51.184491-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded team.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T09:56:25.207432-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T10:53:37.389103-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T10:53:45.353348-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded team.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T10:54:44.129281-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T15:57:15.057067-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T17:02:48.125180-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 155,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T18:26:26.655696-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T18:32:05.731836-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T18:32:06.278459-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T18:40:57.013303-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T18:40:57.257822-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:54.143142-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:54.661830-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:54.815549-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:54.907464-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:55.005289-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:55.109557-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:56.833092-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-10-30T22:09:56.929270-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ],
    "2018-10-31T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-10-31T00:01:01.475919-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      }
    ],
    "2018-11-01T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-11-01T00:00:29.117904-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T18:48:20.215897-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T19:30:43.605080-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 155,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T19:31:37.947427-07:00",
        "exc": "Traceback (most recent call last):\n  File \"core/fairylab/fairylab.py\", line 114, in _try\n    response = item(*args, **dict(kwargs, date=date))\n  File \"/home/pi/filefairy/plugin/statsplus/statsplus.py\", line 422, in _extract_all\n    ret = self._extract(encoded_date, id_)\n  File \"/home/pi/filefairy/plugin/statsplus/statsplus.py\", line 484, in _extract\n    game_log_ = parse_game_log(log_link)\n  File \"/home/pi/filefairy/util/statslab/statslab.py\", line 173, in parse_game_log\n    d = datetime.datetime.strptime(date, '%m/%d/%Y')\n  File \"/usr/lib/python3.5/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"/usr/lib/python3.5/_strptime.py\", line 343, in _strptime\n    (data_string, format))\nValueError: time data '' does not match format '%m/%d/%Y'",
        "levelname": "INFO",
        "lineno": 127,
        "msg": "Disabled statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T19:40:30.818985-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Manual push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.032897-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.530618-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.648067-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.734593-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.824529-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:16.914361-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:18.095484-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 4,
        "date": "2018-11-01T20:12:18.183849-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T20:20:10.205977-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T20:28:03.030927-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 2,
        "date": "2018-11-01T20:33:40.207870-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-01T20:32:26.602473-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 294,
        "msg": "Download failed.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      }
    ],
    "2018-11-02T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-11-02T22:08:55.796530-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:56.302638-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:56.428027-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:56.522537-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:56.621180-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:56.719722-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:57.920616-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:08:58.020323-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:09:19.739226-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:18:43.427037-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-02T22:18:43.911976-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      }
    ],
    "2018-11-03T00:00:00-07:00": [
      {
        "count": 1,
        "date": "2018-11-03T00:01:08.009642-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 184,
        "msg": "Automated push.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T00:53:02.935628-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T02:12:28.973858-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T03:37:56.664549-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1254, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1107, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1152, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1103, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 934, in _send_output\n    self.send(msg)\n  File \"/usr/lib/python3.5/http/client.py\", line 877, in send\n    self.connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 1253, in connect\n    super().connect()\n  File \"/usr/lib/python3.5/http/client.py\", line 849, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n  File \"/usr/lib/python3.5/socket.py\", line 712, in create_connection\n    raise err\n  File \"/usr/lib/python3.5/socket.py\", line 703, in create_connection\n    sock.connect(sa)\nOSError: [Errno 101] Network is unreachable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/urllib_/urllib_.py\", line 15, in urlopen\n    with request.urlopen(url, data=data, timeout=8) as f:\n  File \"/usr/lib/python3.5/urllib/request.py\", line 163, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 466, in open\n    response = self._open(req, data)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 484, in _open\n    '_open', req)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 444, in _call_chain\n    result = func(*args)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1297, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n  File \"/usr/lib/python3.5/urllib/request.py\", line 1256, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>",
        "levelname": "WARNING",
        "lineno": 22,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/urllib_/urllib_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T06:25:41.844016-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T07:23:45.461057-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T10:02:06.618709-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T11:37:19.604373-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T14:05:26.612557-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T15:17:15.006238-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 195,
        "msg": "Tracker locked.",
        "pathname": "/home/pi/filefairy/plugin/exports/exports.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T15:35:30.889750-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T16:05:07.785832-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 155,
        "msg": "Sim in progress.",
        "pathname": "/home/pi/filefairy/plugin/statsplus/statsplus.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T16:13:01.705152-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/usr/lib/python3.5/subprocess.py\", line 385, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 801, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 1447, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/lib/python3.5/subprocess.py\", line 829, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 390, in run\n    stderr=stderr)\nsubprocess.TimeoutExpired: Command '['ssh', 'brunnerj@server', 'ls -l /var/www/html/StatsLab/league_file']' timed out after 8 seconds",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T16:58:42.027286-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 104,
        "msg": "Upload started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:06:25.274436-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 312,
        "msg": "File is up.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:06:26.899457-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 306,
        "msg": "Download started.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:12:17.862371-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 288,
        "msg": "Download finished.",
        "pathname": "/home/pi/filefairy/plugin/leaguefile/leaguefile.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:12:18.252238-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 63,
        "msg": "News updated.",
        "pathname": "/home/pi/filefairy/plugin/recap/recap.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:12:33.453890-07:00",
        "exc": "Traceback (most recent call last):\n  File \"/home/pi/filefairy/util/subprocess_/subprocess_.py\", line 18, in check_output\n    check=True)\n  File \"/usr/lib/python3.5/subprocess.py\", line 398, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Manual push.']' returned non-zero exit status 1",
        "levelname": "WARNING",
        "lineno": 24,
        "msg": "Handled warning.",
        "pathname": "/home/pi/filefairy/util/subprocess_/subprocess_.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:12:45.815371-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 172,
        "msg": "Fetched latest changes.",
        "pathname": "/home/pi/filefairy/plugin/git/git.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:32.050922-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 289,
        "msg": "Restarted fairylab.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:32.583673-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded exports.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:32.739792-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded gameday.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:32.838470-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded git.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:32.941308-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded leaguefile.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:33.051238-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded recap.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:34.790939-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded snacks.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      },
      {
        "count": 1,
        "date": "2018-11-03T17:14:34.894085-07:00",
        "exc": "",
        "levelname": "INFO",
        "lineno": 252,
        "msg": "Reloaded statsplus.",
        "pathname": "/home/pi/filefairy/core/fairylab/fairylab.py"
      }
    ]
  }
}
